apiVersion: v1
kind: Service
metadata:
  name: front-end-lb
  labels:
   app: front-end
  namespace: sock-shop
spec:
  selector: 
    app: front-end
  ports:
    - port: 80
      targetPort: 8079
  type: LoadBalancer
